# Generated by Django 3.0.8 on 2021-01-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('img', models.ImageField(upload_to='static/img/news/')),
            ],
        ),
    ]
