# Generated by Django 3.0.8 on 2021-02-10 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('kind', models.PositiveSmallIntegerField(choices=[(1, 'Кран'), (2, 'Лебедка'), (3, 'Эжектор')], verbose_name='kind')),
                ('category', models.PositiveSmallIntegerField(choices=[(11, 'Судовой'), (12, 'Пирсовый'), (13, 'Съемный портальный'), (14, 'Балки грузовые'), (15, 'Грузовой специальный'), (16, 'Грузовой арктический'), (21, 'Грузовой - перем. ток | мал. ср.'), (22, 'Грузовой - перем. ток | бол.'), (23, 'Пром. Грузовой - эл. привод | мал.'), (24, 'Пром. Грузовой - перем. ток | бол.'), (25, 'Вьюшка топенантная - перем. ток'), (26, 'Подъемно тяговая - перем. ток'), (27, 'Грузовой - перем. ток'), (28, 'Гидрологический'), (29, 'Пром. Лебедка или комплекс'), (210, 'Буксирная автом. эл. привод'), (211, 'Буксирно-технологическая эл. привод'), (212, 'Шлюпочная - гидр. привод'), (217, 'Трелевочная'), (218, 'Люктового закрытия - перем. ток'), (219, 'Траповая - перем. ток'), (31, 'Водоструйный стационарный'), (1, 'Водоструйный переносной')], verbose_name='category')),
                ('img', models.ImageField(blank=True, upload_to='product/')),
                ('text', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='news',
            name='img',
            field=models.ImageField(blank=True, upload_to='news/'),
        ),
    ]
